In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('csv/problem-7-5.csv')

<h3>Problem 7.5</h3>
<p>Anda diberi data anime. Tentukan:</p>

<ol>
    <li>Banyaknya data</li>
    <li>Data anime berjudul "Fullmetal Alchemist: Brotherhood"</li>
    <li>Banyaknya anime dengan jumlah member lebih dari 40.000 dan kecil dari 80.000</li>
    <li>Data anime bertipe OVA dengan jumlah member lebih dari 120.000</li>
    <li>Data anime dengan rating terendah</li>
    <li>Data 10 anime dengan rating tertinggi. Jika ada rating yang sama, urutkan dari member terbanyak</li>
    <li>Tabel frekuensi banyaknya anime setiap jenis</li>
    <li>Rata-rata jumlah episode anime bertipe TV dan bergenre Shounen</li>
    <li>Rata-rata ratung anime bertipe Movie dengan jumlah member lebih dari 100.000</li>
    <li>Standar deviasi jumlah member</li>
    <li>Koefisien korelasi jumlah member dan rating</li>
</ol>

In [3]:
# 1. Banyaknya data
len(df)

9582

In [4]:
# 2. Data anime berjudul "Fullmetal Alchemist: Brotherhood"
df.loc[df['name'] == "Fullmetal Alchemist: Brotherhood"]

,anime_id,name,genre,type,episodes,rating,members
3037,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665

In [5]:
# 3. Banyaknya anime dengan jumlah member lebih dari 40.000 dan kecil dari 80.000
len(df.loc[(df['members'] > 40000) & (df['members'] < 80000)])

494

In [6]:
 # 4. Data anime bertipe OVE dengan jumlah member lebih dari 120.000
 df.loc[(df['type'] == 'OVA') & (df['members'] > 120000)]

,anime_id,name,genre,type,episodes,rating,members
20,44,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,"Action, Drama, Historical, Martial Arts, Roman...",OVA,4,8.83,129307
568,777,Hellsing Ultimate,"Action, Horror, Military, Seinen, Supernatural...",OVA,10,8.59,297454
3713,7059,Black★Rock Shooter (OVA),"Action, Drama, School, Slice of Life",OVA,1,7.24,130665
5566,15037,Corpse Party: Tortured Souls - Bougyakusareta ...,"Horror, Mystery",OVA,4,7.12,126699
5823,16762,Mirai Nikki Redial,"Action, Psychological, Shounen, Supernatural",OVA,1,7.71,135604
6143,18397,Shingeki no Kyojin OVA,"Action, Drama, Fantasy, Shounen, Super Power",OVA,3,7.88,121063

In [7]:
# 5. Data anime dengan rating terendah
df.loc[df['rating'] == df['rating'].min()]

,anime_id,name,genre,type,episodes,rating,members
9577,34476,Platonic Chain: Ansatsu Jikkouchuu,"Sci-Fi, Slice of Life",Special,1,1.67,51

In [8]:
# 6. Data 10 anime dengan rating tertinggi. Jika ada rating yang sama, urutkan dari member terbanyak
df.sort_values(['rating', 'members'], ascending=[False, False])[:10]

,anime_id,name,genre,type,episodes,rating,members
9423,33662,Taka no Tsume 8: Yoshida-kun no X-Files,"Comedy, Parody",Movie,1,10.00,13
6935,23005,Mogura no Motoro,Slice of Life,Movie,1,9.50,62
8946,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
9418,33607,Kahei no Umi,Historical,Movie,1,9.33,44
3037,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
7871,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
7541,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53
4354,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4600,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
9186,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351

In [9]:
# 7. Tabel frekuensi banyaknya anime tiap jenis.
df['type'].value_counts()

TV         3161
Movie      2073
OVA        1839
Special    1469
ONA         573
Music       467
Name: type, dtype: int64

In [10]:
# 8. Rata-rata jumlah anime episode bertipe TV dan bergenre Shounen
df.loc[(df['type'] == "TV") & df['genre'].str.contains('Shounen')]

,anime_id,name,genre,type,episodes,rating,members
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52,7.06,9848
5,15,Eyeshield 21,"Action, Comedy, Shounen, Sports",TV,145,8.08,83648
6,17,Hungry Heart: Wild Striker,"Comedy, Shounen, Slice of Life, Sports",TV,52,7.74,13469
9,20,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
10,22,Prince of Tennis,"Action, Comedy, School, Shounen, Sports",TV,178,8.04,87643
...,...,...,...,...,...,...,...
9061,32648,Handa-kun,"Comedy, Shounen, Slice of Life",TV,12,7.46,69621
9126,32802,Cardfight!! Vanguard G: Stride Gate-hen,"Action, Game, Shounen",TV,24,7.14,2121
9186,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
9310,33255,Saiki Kusuo no Ψ-nan (TV),"Comedy, School, Shounen, Supernatural",TV,120,8.29,47092
9468,33811,Teekyuu 8,"Comedy, Shounen, Sports",TV,12,6.76,3961

In [11]:
# 9. Rata-rata rating anime bertipe Movie dengan jumlah member lebih dari 100.000
df.loc[(df['type'] == 'Movie') & (df['members'] > 100000)]['rating'].mean()

8.210408163265306

In [12]:
# 10. Standar deviasi jumlah member
df['members'].std()

57055.998090349516

In [13]:
# 11. Koefisien korelasi jumlah member dan rating
df['members'].corr(df['rating'])

0.38874055640003247